name: Run Pytest on Push and Pull

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true 

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup Python 3.12
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: 3.12

      # - name: Install dependencies
      #   run: |
      #     python -m pip install -r requirements.txt

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag schemacraft:latest

      # - name: Summon Schemacraft
      #   run: |
      #     docker run --detach schemacraft:latest

      # - name: Run Pytest
      #   run: |
      #     pytest
      
      - name: Run Docker container
        run: |
          docker run --detach schemacraft:latest

      - name: Get container ID
        run: |
          my-app-container-id=$(docker ps -q -f name=my-app-container)  # Adjust container name
          echo "Container ID: $my-app-container-id"

      - name: Wait for container to be ready
        run: |
          until docker ps -q | grep ${{ steps.get_container_id.outputs.my-app-container-id }}; do sleep 5; done
        env:
          my-app-container-id: ${{ steps.get_container_id.outputs.my-app-container-id }}

      - name: Run Pytest in Container
        run: |
          docker run --rm my-app-image pytest